name: GitHub Activity

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare directories
        run: |
          mkdir -p dist-snake
          mkdir -p dist-koipond
          mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist-snake/github-contribution-grid-snake.svg
            dist-snake/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Generate Koipond
        uses: 0xydev/koipond@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist-koipond/koipond-light.svg
            dist-koipond/koipond-dark.svg?theme=dark

      - name: Merge outputs
        run: |
          cp dist-snake/* dist/
          cp dist-koipond/* dist/

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
